version: '3.7'
services:
  mysql:
    container_name: mysql_server
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: asas
      cap_add: SYS_NICE

  backend:
    environment:
      DB_AIM_IP: mysql_server
      DB_AIM_USERNAME: root
      DB_AIM_PASSWORD: asas
      DB_AIM_USER_ROLE_ADMIN_USERNAME: sprzedam
      DB_AIM_USER_ROLE_ADMIN_PASSWORD: opla
      AIM_AI_DOMAIN_NAME: ai
    depends_on: [mysql]
    container_name: backend
    image: syskaseb/aimachine-backend
    restart: always

  frontend:
    depends_on: [mysql, backend]
    container_name: frontend
    image: syskaseb/aimachine-frontend

  ai:
    environment:
      PYTHONUNBUFFERED: 1
      AIM_BACKEND_DOMAIN_NAME: backend
    depends_on: [mysql, backend, frontend]
    container_name: ai
    image: syskaseb/aimachine-ai

  reverse_proxy:
    depends_on: [frontend, backend, ai]
    container_name: nginx
    volumes: [~/nginx.conf:/etc/nginx/nginx.conf]
    image: nginx:mainline-alpine
    ports: [80:80, 8080:8080]
